### ISSUE TITLE
DEP Support

### ISSUE THREAD

**Issue by ozguncagri** [yittg/ving#1]
Using [dep](https://github.com/golang/dep) for dependency management could be great. Installing all dependencies on global stash is not that great thing for building it.

**Comment by yittg** [comment]
Hi @ozguncagri, this project use go modules for dependency management which introduced from [go1.11](https://golang.org/doc/go1.11), it's really not very friendly to users using older versions, I will try to make it compatible though. Thank you. 😄

**Comment by ozguncagri** [comment]
Oh I wasn't noticed that 😅 I'm actually using go1.11 but my eyes are searching dep related files at first glance because I get used to dep 😃 Go mod is also great tool 👌

**Comment by yittg** [comment]
👌  i'll close this issue. Feel free to give more feedback, thanks again.
