### ISSUE TITLE
Improvements for traceroute functionality

### ISSUE THREAD

**Issue by james-antill** [yittg/ving#10]
A couple of things that might help:

1. Don't stop the trace when you hit any error. It's somewhat common for certain hops to just send error codes back instead of responding properly, but the next hop will respond fine.

2. It's a common optimisation to send all of the hops at once, using incrementing port numbers for each hop (Eg. each hop is starting port+ttl-1, so you can check the port number to see which hop the response is from).

3. Might be nice to have a command line option to automatically start it, esp. if there's only a single host.

**Comment by yittg** [comment]
> Might be nice to have a command line option to automatically start it, esp. if there's only a single host.
This now is available.

**Comment by yittg** [comment]
The first, and second proposal may need more consideration to make it more comfortable. 😸

**Comment by yittg** [comment]
Hi @james-antill, the first and third is now committed. As for the second proposal, it seems to me that is less necessary, at least for the moment. Or can you tell me about the inconvenience without implementing it?

**Comment by james-antill** [comment]
It's fine, 2 just gets you the results faster.
