### ISSUE TITLE
Need root privilege On Linux arch

### ISSUE THREAD

**Issue by barryz** [yittg/ving#2]
start ping error, socket: permission denied

**Comment by jfkw** [comment]
I also see this error on Gentoo Linux ~amd64, not specific to ubuntu Can you edit the title to reflect the error message? Same error message whether `ving` is invoked as normal user, nomal user with sudo or as root.

**Comment by yittg** [comment]
hi @barryz @jfkw , it's probably a common issue for a ping-like process, i'll take a close look at it. btw, this project internally use non-privileged mode mentioned in [doc](https://godoc.org/golang.org/x/net/icmp#ListenPacket), which may not cover all scenarios. And thanks for your feedback, i'll try to fix it ASAP.

**Comment by gustavosbarreto** [comment]
on Arch linux:

```
$ sudo ving 8.8.8.8
start ping error, socket: permission denied
```
