### ISSUE TITLE
Include traceroute functionality, for multiple hosts, somewhat like mtr

### ISSUE THREAD

**Issue by james-antill** [yittg/ving#3]
Output looks really nice but when there are problems I almost always reach for "mtr" now because you'll actually see where the problem is, adding this might not be too hard for info. look at:

https://serverfault.com/questions/374620/does-traceroute-use-udp-or-icmp-or-both#

Can also try/display this only if the pings are "bad", as termui should help you get to a nicer output easier.

**Comment by yittg** [comment]
Hi @james-antill, great advice. actually i'm thinking about how to display the err msg and cause to make sense when pings are "bad" like you say. thanks for your advice and link. 😄

**Comment by james-antill** [comment]
It's pretty cool. A couple of things that might help though:

1. Don't stop the trace when you hit any error. It's somewhat common for certain hops to just send error codes back instead of responding properly, but the next hop will respond fine.

2. It's a common optimisation to send all of the hops at once, using incrementing port numbers for each hop (Eg. each hop is starting port+ttl-1, so you can check the port number to see which hop the response is from).

3. Might be nice to have a command line option to automatically start it, esp. if there's only a single host.

**Comment by yittg** [comment]
Thanks for your feedbacks, would you mind to open a new issue for these improvements 😄
