### ISSUE TITLE
start ping error, socket: permission denied

### ISSUE THREAD

**Issue by eladile** [yittg/ving#5]
On my ubuntu 18.04 ving won't work.
Followed all instructions including 'sudo setcap "cap_net_raw+ep" ving' but still get the above error.
Running it with sudo or under root user also didn't help.

> ving 8.8.8.8

> start ping error, socket: permission denied

**Comment by yittg** [comment]
Could you provide the git hash (no version this moment), this issue should be fixed after `e8b593d`, 
just run `go get -u` to update to the latest version if not, or did you mean that the issue still exists even after you did that.

**Comment by eladile** [comment]
Oh thank you! I rebased and all works great,  sorry for bothering you :+1:
